version: '3.8'

services:
  ubuntu:
    image: ubuntu:22.04
    container_name: comp_ling_fourth_lab_work
    user: root
    stdin_open: true
    tty: true
    volumes:
      - "./:/home/user/comp_ling_fourth_lab_work"
